### ISSUE TITLE
Create option to download the mobile apps

### ISSUE THREAD

**Issue by izacristina** [systers/pchub#10]
[US01 - Show information about mobile apps](https://trello.com/c/pyAR0JQK)

Similar to [MACC](http://pc-web-dev.systers.org/download/), iOS should go to AppStore and Android should go to Google Play.

**Comment by bethanyr** [comment]
It looks like there is an option to add the url for the Appstore or Google Play, but on the mobile apps page - the `Go to the app download` link does not have the correct URL - it is appending the pchub url to the front of the mobile app download url.

**Comment by bethanyr** [comment]
I have created a new issue to track the bug - [#40](https://github.com/systers/pchub/issues/40) - I am closing this issue as the feature is completed.
