### ISSUE TITLE
Create user registration

### ISSUE THREAD

**Issue by izacristina** [systers/pchub#11]
**As an** user, **I want to** register my information in the application, **so that** I can access the application resources

**Acceptance Criteria:**
- [x] 1) Register full Name 
- [x] 2) Register name that the user want to be called as an optional field (nickname)
- [x] 2) Register email address
- [x] 3) Register Location or Assignment (may be free form field for cities)
- [x] 4) Register Profile link (optional)
- [x] 5) Free form field for additional information
- [ ] 6) Allow registration with github, facebook, twitter and linkedin

**Comment by bethanyr** [comment]
I propose we close this issue, and create a new issue for this task: Allow registration with github, facebook, twitter and linkedin

**Comment by bethanyr** [comment]
I have created a new issue for the remaining task: [#42](https://github.com/systers/pchub/issues/42)
