### ISSUE TITLE
Make user login

### ISSUE THREAD

**Issue by izacristina** [systers/pchub#13]
**As an** user, **I want to** make login on the application, **so that** I can access the application resources.

**Acceptance Criteria:**
- [x] 1) Admins can only login if their account was approved by other admin or superadmin
- [x] 2) Staff and volunteers can login if they register your account

[Click here to see the screencast for review](https://youtu.be/XBe7jFBheBE)

**Comment by bethanyr** [comment]
I think this issue can be closed, I am able to create an account.
