### ISSUE TITLE
User (Adminstrator) is not verified

### ISSUE THREAD

**Issue by daisyab** [systers/pchub#19]
The 'signing up as an administrator' functionality is not functional because the user's account never gets approved.

![admin](https://cloud.githubusercontent.com/assets/6463437/17201319/40dc461c-5485-11e6-8796-97a5d66516cc.png)

**Comment by izacristina** [comment]
This is cause a new administrator always need to be approved by a superadmin

**Comment by daisyab** [comment]
There is no superadmin created in the installation of the PCHub.
This also means that no users can be/are administrators.
