### ISSUE TITLE
Add an application

### ISSUE THREAD

**Issue by izacristina** [systers/pchub#20]
**As an** administrator, **I want to**  add a new application, **so that** I can create a page with the application information.

**Acceptance Criteria:**
- [x] 1) There must be an interface to the administrator add the application information, which generates a page with the information provided
- [x] 2) The application add form should request the application name, description and links
- [x] 3) Only administrators can add new applications

**Comment by bethanyr** [comment]
It appears this issue has been completed, am closing the issue.
