### ISSUE TITLE
Search Bar functionality error produced with no users.

### ISSUE THREAD

**Issue by daisyab** [systers/pchub#21]
When no users have signed up, the search bar functionality produces an Access Denied error.

![search1](https://cloud.githubusercontent.com/assets/6463437/17274720/f812110a-56e6-11e6-91cd-47952aedf0e7.png)

When users register/signup, the search bar functionality works ok.

![searchbar2](https://cloud.githubusercontent.com/assets/6463437/17274726/269b97d0-56e7-11e6-9c72-558c8e4f6504.png)

**Comment by izacristina** [comment]
This is cause just users logged in can search for others users, but I need to handle this exception, thank you
