### ISSUE TITLE
Search Applications

### ISSUE THREAD

**Issue by izacristina** [systers/pchub#24]
**As an** user, **I want to**  search for applications, **so that** I can see their information.

**Acceptance Criteria:**
- [x] 1) For admins or superadmins should appear options to edit or delete the application.
- [x] 2) Any user can search for applications

**Comment by rosariorobinson** [comment]
What does it mean to edit/delete an application? another PC administrator can delete an application? E.g. Malaria, etc.?

**Comment by izacristina** [comment]
Yes

**Comment by bethanyr** [comment]
I have checked and am able to search for applications, am closing this issue.
