### ISSUE TITLE
Edit/Delete user

### ISSUE THREAD

**Issue by izacristina** [systers/pchub#26]

**Comment by bethanyr** [comment]
I just tested locally and tried updating the city and nickname fields for my account, but I don't see that they were updated correctly in the database. I did confirm that I can cancel my account and it is deleted from the database.

I think this issue can be resolved once you are able to update your profile and the changes are saved to the database.

**Comment by bethanyr** [comment]
I have created a bug issue [#41](https://github.com/systers/pchub/issues/41) and will resolve this issue.
