### ISSUE TITLE
Update ReadME with setup project setup instructions

### ISSUE THREAD

**Issue by rosariorobinson** [systers/pchub#30]
Hi @izacristina ... @MeepyMay and I are trying to prepare for GHC Open source day and we need help with the ReadME.  Can you help with updating the ReadME with more specifics on setup? The goal is to environment ready on a USB in case there are WiFi issues. 

Is it possible to have README updated by Friday or Saturday (10/14 or 10/15 respectively) at the latest? We really need your help. 

Please use this issue to update us on this task.

**Comment by izacristina** [comment]
I can do it on Saturday

**Comment by izacristina** [comment]
@rosariorobinson @MeepyMay What do you want to keep in the README, of the requirements that are there?

**Comment by bethanyr** [comment]
It looks like this issue is still relevant - and would be great to have clearer instructions on getting the app setup and running - including the versions of Ruby, Rails and SQLlite.

**Comment by Rupinderwadali** [comment]
Yes. We can do one more thing with this. Includes the link of blog post which includes project setup instructions.
Just a suggestion

**Comment by Rupinderwadali** [comment]
@jericahuang Try to the generate edge cases as well. Like, install the application on a new machine (fresh machine) with no previous installation of any dependency. This will generate the edge cases while installing the application.
