### ISSUE TITLE
Wiki Sidebar Update

### ISSUE THREAD

**Issue by ExactlyMay** [systers/pchub#39]
## Description
As a newcomer,
I need to navigate the repo successfully,
so that I can understand where the project is in its development.

## Mocks
![screen shot 2018-04-19 at 3 47 20 pm](https://user-images.githubusercontent.com/2440938/39014663-06dcb230-43e9-11e8-997c-96a89b7c55e8.png)

### Update [Required]
- [x] Update to [the template](https://docs.google.com/document/d/1h53P1h5g9hWEUsnOhpl9PgVzbWEGhTMIP2Pyta-MYSA/edit?usp=sharing) as discussed by the Community.
### Enhancement to Update [Optional]
- [x] Link all GSoC/Outreachy student's pages if applicable.
- [x] Link Final Reports page if applicable.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 3 Community Members.

## Estimation
10-30 minutes

**Comment by jericahuang** [comment]
Github doesn't seem to support forking and creating PRs for wiki pages. I followed the guide [here](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) that someone linked in Slack. My "clone" is [here](https://github.com/jericahuang/pchub-wiki).

**Comment by jericahuang** [comment]
Thanks @bethanyr , I updated my clone.

**Comment by bethanyr** [comment]
cool - I see the updates @jericahuang.  On the Mock-up - the `Getting Started` is the 3rd item - and you have it in the documentation section (I know - nitpicky, not sure how close it needs to be to the mock-up, but it probably is nice to be consistent). Otherwise I think it looks good.

**Comment by jericahuang** [comment]
Agreed, it's best to be consistent. Updated again 👍  @bethanyr

**Comment by bethanyr** [comment]
it looks good to me. 👍 . Maybe post a note in the #pc-hub slack channel asking others to review.

**Comment by Vaibhavi24** [comment]
@jericahuang The Setup and Install link to Readme.md looks broken.

**Comment by jericahuang** [comment]
@Vaibhavi24 You're right, it is broken in the .textile file preview on Github (https://github.com/jericahuang/pchub-wiki/blob/master/_Sidebar.textile) but when it is converted to markdown, it works. I tested it out on http://markdownlivepreview.com/. This screenshot doesn't show my cursor, but I am hovering over Setup and Install, and the link preview in the bottom left does link to the README.
<img width="956" alt="screen shot 2018-05-17 at 4 37 35 pm" src="https://user-images.githubusercontent.com/8077898/40202639-a323b22a-59f0-11e8-89f4-a9568b4e03a7.png">

**Comment by Vaibhavi24** [comment]
@jericahuang Okay! The updates look good to me :+1:

**Comment by jericahuang** [comment]
As discussed in the call, 3 mentors approved the changes and I've committed them! Closing.
