### ISSUE TITLE
Allow registration with github, facebook, twitter and linkedin accounts

### ISSUE THREAD

**Issue by bethanyr** [systers/pchub#42]
## Description
As a new user,
I need register with PC Hub and would like to use my github, facebook, twitter or linkedin accounts,
so that I do not have to create a new login and password and can provide feedback on PC apps.

## Mocks
N/A

### Update [Required]
- [ ] Add option to register using a github account
- [ ] Add option to register using a facebook account
- [ ] Add option to register using a twitter account
- [ ] Add option to register using a linked in account
- [ ] Unit tests created
### Enhancement to Update [Optional]
N/A

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
40 hours

**Comment by Rupinderwadali** [comment]
If we are using the social login then we don’t need to setup it for registration. 
As we can add the social login for sign in. If user is new and don’t want to create account he/she can login via social login. If user is not registered then we will save the data in db

**Comment by bethanyr** [comment]
We have implemented github signup as part of GSOC 2018 work, we do not have requirements for integration with facebook, twitter and linked in - so am closing this issue.
