### ISSUE TITLE
UI Mockups - Sign in / Sign-up page

### ISSUE THREAD

**Issue by AngieSky** [systers/pchub#45]
## Description
As a user,
I need make mockups,
so that I can make appropriate UI changes.

## Mocks
![signup-1](https://user-images.githubusercontent.com/8077898/40278116-28aa4292-5bf9-11e8-9e77-b47a3aa8b085.jpg)
![signup-2](https://user-images.githubusercontent.com/8077898/40278487-c2ab99da-5bff-11e8-94d7-6dcb8bd174b8.jpg)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by bethanyr** [comment]
Is the plan to limit who can sign-up for accounts to only those with peacecorps email or github accounts? Is there another type of user who might need to sign-up? 

Will a peacecorps user no longer be able to choose which role they are signing up for?

**Comment by jericahuang** [comment]
Is the plan to limit who can sign-up for accounts to only those with peacecorps email or github accounts? Right

Is there another type of user who might need to sign-up? Unsure. Maybe in these cases the admin can manually change the role after the user signs up with one of the existing options. What does everyone else think?

Will a peacecorps user no longer be able to choose which role they are signing up for? They will! Accidentally left that out in my mockup.
