### ISSUE TITLE
Peace Corps logo to link to root

### ISSUE THREAD

**Issue by jericahuang** [systers/pchub#57]
## Description
As a user,
I need to be able to navigate the page intuitively.

Linking the Peace Corps logo in the upper left corner to the homepage can help accomplish that.

## Mocks
No visual changes.

### Update [Required]
- [ ] Top-left image links to the page root

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Vaibhavi24** [comment]
Yes, this seems a valid issue!
