### ISSUE TITLE
Project Scope Document

### ISSUE THREAD

**Issue by MeepyMay** [systers/pchub#7]
@izacristina had asked about project requirements. I created the following document to help guide her.

@izacristina will create implementation and timelines based on 2 week SCRUM methodology. She's working with @daisyab as well (AUT GSoC 2016 student). The implementation and timeline section should be updated every two weeks.

[PCHUB_ProjectReq.docx](https://github.com/systers/pchub/files/296491/PCHUB_ProjectReq.docx)

**Comment by bethanyr** [comment]
I think we can close this issue, I don't see any tasks that can be completed, it looks like it was used to kick off the GSOC 2016 work.
